# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dotstrap 0.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "dotstrap"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["William Myers"]
  s.date = "2015-10-31"
  s.description = "bootstrap your shell dotfiles in parallel from GitHub repos"
  s.email = "mkwmms@icloud.com"
  s.executables = ["ds"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CONTRIBUTING.md",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/ds",
    "dotstrap.gemspec",
    "lib/dotstrap.rb",
    "lib/dotstrap/configuration.rb",
    "lib/dotstrap/git.rb",
    "lib/dotstrap/shell.rb",
    "spec/bundle_spec.rb",
    "spec/shell_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mkwmms/dotstrap"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = nil

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<parallel>, ["~> 1.6"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.3"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_development_dependency(%q<factory_girl>, ["~> 4.0"])
    else
      s.add_dependency(%q<parallel>, ["~> 1.6"])
      s.add_dependency(%q<commander>, ["~> 4.3"])
      s.add_dependency(%q<rspec>, ["~> 3.3"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_dependency(%q<factory_girl>, ["~> 4.0"])
    end
  else
    s.add_dependency(%q<parallel>, ["~> 1.6"])
    s.add_dependency(%q<commander>, ["~> 4.3"])
    s.add_dependency(%q<rspec>, ["~> 3.3"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
    s.add_dependency(%q<factory_girl>, ["~> 4.0"])
  end
end

