# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: reel 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "reel"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["William Myers"]
  s.date = "2015-09-30"
  s.description = "Downloads repositories from GitHub in parallel and symbolically links and/or creates a file to be sourced according to your shell (fish, zsh, bash)"
  s.email = "mkwmms@no-reply.github.com"
  s.executables = ["reel"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".github-todos",
    ".rspec",
    "CONTRIBUTING.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/reel",
    "lib/reel.rb",
    "lib/reel/bundle.rb",
    "lib/reel/git.rb",
    "lib/reel/shell.rb",
    "lib/reel/update.rb",
    "reel.gemspec",
    "spec/bundle_spec.rb",
    "spec/shell_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mkwmms/reel"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Download & install shell config files from GitHub repos"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<parallel>, ["~> 1.6"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.3"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_development_dependency(%q<factory_girl>, ["~> 4.0"])
    else
      s.add_dependency(%q<parallel>, ["~> 1.6"])
      s.add_dependency(%q<commander>, ["~> 4.3"])
      s.add_dependency(%q<rspec>, ["~> 3.3"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_dependency(%q<factory_girl>, ["~> 4.0"])
    end
  else
    s.add_dependency(%q<parallel>, ["~> 1.6"])
    s.add_dependency(%q<commander>, ["~> 4.3"])
    s.add_dependency(%q<rspec>, ["~> 3.3"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
    s.add_dependency(%q<factory_girl>, ["~> 4.0"])
  end
end

