DROP TABLE IF EXISTS Batch;
DROP TABLE IF EXISTS Field;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Record;
DROP TABLE IF EXISTS User;


CREATE TABLE Batch 
(
	ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , 
	FilePath TEXT NOT NULL , 
	ProjectID INTEGER NOT NULL , 
	State TEXT NOT NULL 
)

CREATE TABLE Field 
(
	ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , 
	ProjectID INTEGER NOT NULL , 
	FieldPath TEXT NOT NULL , 
	KnownPath TEXT NOT NULL ,
	Width INTEGER NOT NULL , 
	XCoordinate INTEGER NOT NULL , 
	Number INTEGER NOT NULL , 
	Title TEXT NOT NULL  UNIQUE 
)

CREATE TABLE Project 
(
	ID INTEGER PRIMARY KEY  NOT NULL ,
	Name TEXT NOT NULL ,
	RecordsPerBatch INTEGER NOT NULL ,
	FirstYCoord INTEGER, 
	RecordHeight INTEGER
)

CREATE TABLE Record 
(
	ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , 
	RowOnImage INTEGER NOT NULL , 
	BatchID INTEGER NOT NULL , 
	Data TEXT NOT NULL , 
	FieldID INTEGER NOT NULL 
)

CREATE TABLE User 
(
	ID INTEGER PRIMARY KEY  NOT NULL  UNIQUE , 
	username TEXT NOT NULL  UNIQUE , 
	password TEXT NOT NULL , 
	FirstName TEXT NOT NULL , 
	LastName TEXT NOT NULL , 
	Email TEXT NOT NULL  UNIQUE , 
	RecordCount INTEGER NOT NULL , 
	CurrentBatch INTEGER NOT NULL 
)
